# To NumPy

Explore how to convert a `pandas` `DataFrame` with categorical data into a fully quantitative `NumPy` matrix suitable for machine learning. Learn to filter data, handle missing values, and transform categorical features into indicator variables using `pandas` `get_dummies`. This lesson equips you to prepare real-world datasets for input into machine learning frameworks.

### Chapter Goals

* Learn how to convert a `DataFrame` to a `NumPy` matrix
* Write code to modify an MLB dataset and convert it to a `NumPy` matrix

---

## A. Machine learning

The `DataFrame` object is great for storing a dataset and performing data analysis in Python. However, most machine learning frameworks (e.g. TensorFlow), work directly with `NumPy` data. Furthermore, the `NumPy` data used as input to machine learning models must solely contain quantitative values.

Therefore, to use a `DataFrame`'s data with a machine learning model, we need to convert the `DataFrame` to a `NumPy` matrix of quantitative data. So even the categorical features of a `DataFrame`, such as gender and birthplace, must be converted to quantitative values.

---

## B. Indicator features

When converting a `DataFrame` to a `NumPy` matrix of quantitative data, we need to find a way to modify the categorical features in the `DataFrame`.

The easiest way to do this is to convert each categorical feature into a set of indicator features for each of its categories. The indicator feature for a specific category represents whether or not a given data sample belongs to that category.

The code below shows a `DataFrame` with indicator features.

```python
# predefined non-indicator DataFrame
print('{}\n'.format(df))

# predefined indicator Dataframe
print('{}\n'.format(indicator_df))
```

In the code above, the `DataFrame` `df` has a single categorical feature called `Color`. The corresponding indicator features for `Color` are shown in `indicator_df`.

> **Note:** Note that an indicator feature contains 1 when the row has that particular category, and 0 if the row does not.

---

## C. Converting to indicators

In `pandas`, we convert each categorical feature of a `DataFrame` to indicator features with the `get_dummies` function. The function takes in a `DataFrame` as its required argument, and returns the `DataFrame` with each of its categorical features converted to indicator features.

The code below demonstrates how to use the `get_dummies` function.

```python
# predefined df
print('{}\n'.format(df))

converted = pd.get_dummies(df)
print('{}\n'.format(converted.columns))

print('{}\n'.format(converted[['teamID_BOS',
                               'teamID_PIT']]))
print('{}\n'.format(converted[['lgID_AL',
                               'lgID_NL']]))
```

> **Note:** Note that the indicator features have the original categorical feature's label as a prefix. This makes it easy to see where each indicator feature originally came from.

---

## D. Converting to NumPy

After converting all the categorical features to indicator features, the `DataFrame` should have all quantitative data. We can then convert to a `NumPy` matrix using the `values` function.

The code below converts a `DataFrame`, `df` into a `NumPy` matrix.

```python
# predefined indicator df
print('{}\n'.format(df))

n_matrix = df.values
print(repr(n_matrix))
```

The rows and columns of the output matrix correspond to the rows and columns of the same position in the `DataFrame`. In the code above, the first column of the `NumPy` matrix represents `HR`, the second column represents `teamID_BOS`, and the third column represents `teamID_PIT`.

---

## Time to Code!

The code exercise for this chapter will be to convert a `DataFrame` of MLB statistics (`df`) into a `NumPy` matrix.

1. We only want the data in `df` to be from the current century, so we need to first apply a filter.
Filter `df` for rows where `'yearID'` is at least 2000, then reset `df` equal to the filtered output.
2. We also don't want any of the `NaN` values in our data. We can filter those out using the special `dropna` function.
Set `df` equal to `df.dropna` applied with no arguments.
3. Finally, we want to convert each categorical feature into a set of indicator features for each of its categories.
Then we can convert `df` into a `NumPy` matrix.
Set `df` equal to `pd.get_dummies` with `df` as the only argument.
Set `matrix` equal to `df.values`.

In [5]:
import pandas as pd

data = {
    "playerID": [
        "ohtansh01",
        "judgear01",
        "bettsmo01",
        "sotoju01",
        "acunaro01",
        "freemfr01",
    ],
    "yearID": [2023, 2023, 2023, 2023, 2023, 2023],
    "stint": [1, 1, 1, 1, 1, 1],
    "teamID": ["LAD", "NYA", "LAD", "SDN", "ATL", "LAD"],
    "lgID": ["NL", "AL", "NL", "NL", "NL", "NL"],
    "G": [135, 106, 152, 162, 159, 161],
    "AB": [498, 367, 584, 568, 643, 637],
    "R": [102, 79, 126, 97, 149, 131],
    "H": [151, 112, 179, 156, 217, 211],
    "2B": [26, 16, 40, 32, 35, 59],
    "3B": [8, 0, 1, 1, 4, 2],
    "HR": [44, 37, 39, 35, 41, 29],
    "RBI": [95, 75, 107, 109, 106, 102],
    "SB": [20, 2, 14, 12, 73, 23],
    "CS": [6, 0, 3, 3, 14, 3],
    "BB": [91, 88, 96, 132, 80, 72],
    "SO": [143, 130, 107, 132, 84, 121],
    "IBB": [21, 16, 14, 11, 3, 12],
    "HBP": [0, 0, 4, 4, 2, 8],
    "SH": [0, 0, 0, 0, 0, 0],
    "SF": [3, 3, 5, 5, 5, 5],
    "GIDP": [9, 15, 5, 18, 15, 6],
    "BA": [0.304, 0.305, 0.307, 0.275, 0.337, 0.331],
    "OBP": [0.412, 0.440, 0.408, 0.410, 0.416, 0.410],
    "SLG": [0.654, 0.676, 0.579, 0.519, 0.596, 0.567],
    "OPS": [1.066, 1.116, 0.987, 0.929, 1.012, 0.977],
    "Salary": [30000000, 40000000, 25000000, 23000000, 17000000, 27000000],
}

df = pd.DataFrame(data)
df

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,IBB,HBP,SH,SF,GIDP,BA,OBP,SLG,OPS,Salary
0,ohtansh01,2023,1,LAD,NL,135,498,102,151,26,...,21,0,0,3,9,0.304,0.412,0.654,1.066,30000000
1,judgear01,2023,1,NYA,AL,106,367,79,112,16,...,16,0,0,3,15,0.305,0.440,0.676,1.116,40000000
2,bettsmo01,2023,1,LAD,NL,152,584,126,179,40,...,14,4,0,5,5,0.307,0.408,0.579,0.987,25000000
3,sotoju01,2023,1,SDN,NL,162,568,97,156,32,...,11,4,0,5,18,0.275,0.410,0.519,0.929,23000000
4,acunaro01,2023,1,ATL,NL,159,643,149,217,35,...,3,2,0,5,15,0.337,0.416,0.596,1.012,17000000
5,freemfr01,2023,1,LAD,NL,161,637,131,211,59,...,12,8,0,5,6,0.331,0.410,0.567,0.977,27000000

In [7]:
df = df[df['yearID'] >= 2000]
df = df.dropna()
df

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,IBB,HBP,SH,SF,GIDP,BA,OBP,SLG,OPS,Salary
0,ohtansh01,2023,1,LAD,NL,135,498,102,151,26,...,21,0,0,3,9,0.304,0.412,0.654,1.066,30000000
1,judgear01,2023,1,NYA,AL,106,367,79,112,16,...,16,0,0,3,15,0.305,0.440,0.676,1.116,40000000
2,bettsmo01,2023,1,LAD,NL,152,584,126,179,40,...,14,4,0,5,5,0.307,0.408,0.579,0.987,25000000
3,sotoju01,2023,1,SDN,NL,162,568,97,156,32,...,11,4,0,5,18,0.275,0.410,0.519,0.929,23000000
4,acunaro01,2023,1,ATL,NL,159,643,149,217,35,...,3,2,0,5,15,0.337,0.416,0.596,1.012,17000000
5,freemfr01,2023,1,LAD,NL,161,637,131,211,59,...,12,8,0,5,6,0.331,0.410,0.567,0.977,27000000

In [8]:
df = pd.get_dummies(df)
df

,yearID,stint,G,AB,R,H,2B,3B,HR,RBI,...,playerID_freemfr01,playerID_judgear01,playerID_ohtansh01,playerID_sotoju01,teamID_ATL,teamID_LAD,teamID_NYA,teamID_SDN,lgID_AL,lgID_NL
0,2023,1,135,498,102,151,26,8,44,95,...,False,False,True,False,False,True,False,False,False,True
1,2023,1,106,367,79,112,16,0,37,75,...,False,True,False,False,False,False,True,False,True,False
2,2023,1,152,584,126,179,40,1,39,107,...,False,False,False,False,False,True,False,False,False,True
3,2023,1,162,568,97,156,32,1,35,109,...,False,False,False,True,False,False,False,True,False,True
4,2023,1,159,643,149,217,35,4,41,106,...,False,False,False,False,True,False,False,False,False,True
5,2023,1,161,637,131,211,59,2,29,102,...,True,False,False,False,False,True,False,False,False,True

In [9]:
matrix = df.values
matrix

array([[2023, 1, 135, 498, 102, 151, 26, 8, 44, 95, 20, 6, 91, 143, 21,
        0, 0, 3, 9, 0.304, 0.412, 0.654, 1.066, 30000000, False, False,
        False, False, True, False, False, True, False, False, False,
        True],
       [2023, 1, 106, 367, 79, 112, 16, 0, 37, 75, 2, 0, 88, 130, 16, 0,
        0, 3, 15, 0.305, 0.44, 0.676, 1.116, 40000000, False, False,
        False, True, False, False, False, False, True, False, True,
        False],
       [2023, 1, 152, 584, 126, 179, 40, 1, 39, 107, 14, 3, 96, 107, 14,
        4, 0, 5, 5, 0.307, 0.408, 0.579, 0.987, 25000000, False, True,
        False, False, False, False, False, True, False, False, False,
        True],
       [2023, 1, 162, 568, 97, 156, 32, 1, 35, 109, 12, 3, 132, 132, 11,
        4, 0, 5, 18, 0.275, 0.41, 0.519, 0.929, 23000000, False, False,
        False, False, False, True, False, False, False, True, False,
        True],
       [2023, 1, 159, 643, 149, 217, 35, 4, 41, 106, 73, 14, 80, 84, 3,
        2, 0, 5, 15, 0.337, 0.416, 0.596, 1.012, 17000000, True, False,
        False, False, False, False, True, False, False, False, False,
        True],
       [2023, 1, 161, 637, 131, 211, 59, 2, 29, 102, 23, 3, 72, 121, 12,
        8, 0, 5, 6, 0.331, 0.41, 0.567, 0.977, 27000000, False, False,
        True, False, False, False, False, True, False, False, False,
        True]], dtype=object)