# 02. Contact List

## DataFrame

A DataFrame is the heart of the Pandas library. Think of it like an Excel spreadsheet or SQL table we can control with Python code. It's a 2-dimensional data structure made up of rows and columns. Each column has a name and a data type (like numbers, text, or even dates).

With DataFrames, it's super easy to sort, filter, group, modify, and analyze data.

## Create from a Dictionary (Common)

This is the most popular way to build a DataFrame from scratch:

In [1]:
import pandas as pd

data_dict = {
  'city': ['Brooklyn', 'Seoul', 'Barcelona', 'Mexico City'],
  'country': ['US', 'South Korea', 'Spain', 'Mexico'],
  'population': [2646000, 9411000, 1636000, 9209944]
}

df_dict = pd.DataFrame(data_dict)
df_dict

          city      country  population
0     Brooklyn           US     2646000
1        Seoul  South Korea     9411000
2    Barcelona        Spain     1636000
3  Mexico City       Mexico     9209944

Each key in the data dictionary (city, country, population) becomes a column, and each index in the lists will become a row.

Once the dictionary is created, we can pass the dictionary to pd.DataFrame() to create the DataFrame. Here, we stored it in a variable named df, short for DataFrame.

We can display the DataFrame with its name:

df_dict

## Create from a List of Lists

Sometimes it’s easier to think in rows. We can do that like this with a 2D list:

In [3]:
data_list = [
    ["Brooklyn", "US", 2646000],
    ["Seoul", "South Korea", 9411000],
    ["Barcelona", "Spain", 1636000],
    ["Mexico City", "Mexico", 9209944],
]

df_list = pd.DataFrame(data_list, columns=["city", "country", "population"])
df_list

          city      country  population
0     Brooklyn           US     2646000
1        Seoul  South Korea     9411000
2    Barcelona        Spain     1636000
3  Mexico City       Mexico     9209944

Here, each inner list is a row. Don’t forget to name our columns with the columns parameter!

## Import from a CSV File

Let's say we have a .csv (Comma-Separated Values) file sitting on our computer that we want to bring into Python. We can load it into Pandas in one line with .read_csv():

In [4]:
df_csv = pd.read_csv("matches_clean.csv")
df_csv

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,result,is_competitive,home_rank,home_rank_points,away_rank,away_rank_points
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False,D,0,211.0,0.00,211.0,0.00
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False,H,0,211.0,0.00,211.0,0.00
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False,H,0,211.0,0.00,211.0,0.00
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False,D,0,211.0,0.00,211.0,0.00
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False,H,0,211.0,0.00,211.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49457,2026-07-12,Argentina,Switzerland,3.0,1.0,FIFA World Cup,Unknown,World,True,H,1,1.0,1867.25,20.0,1625.16
49458,2026-07-14,France,Spain,0.0,2.0,FIFA World Cup,Unknown,World,True,A,1,2.0,1859.78,3.0,1853.27
49459,2026-07-15,England,Argentina,1.0,2.0,FIFA World Cup,Unknown,World,True,A,1,4.0,1813.81,1.0,1867.25
49460,2026-07-18,France,England,4.0,6.0,FIFA World Cup,Unknown,World,True,A,1,2.0,1859.78,4.0,1813.81
49461,2026-07-19,Spain,Argentina,1.0,0.0,FIFA World Cup,Unknown,World,True,H,1,3.0,1853.27,1.0,1867.25

# Task

First things first, import pandas at the top of the file.

Then, create a DataFrame named contacts containing information about your friends, family, or fictional characters. Your DataFrame should have at least 3 columns and 4 rows.

In [ ]:
import pandas as pd

friends = {
    "name": ["Bart", "Lisa", "Homer", "Marge"],
    "age": [10, 8, 39, 36],
    "phone_number": ["939-555-0113", "939-555-0114", "939-555-0115", "939-555-0116"],
    "astrological_sign": ["Taurus", "Virgo", "Taurus", "Pisces"],
}

df = pd.DataFrame(friends)
df

    name  age  phone_number astrological_sign
0   Bart   10  939-555-0113            Taurus
1   Lisa    8  939-555-0114             Virgo
2  Homer   39  939-555-0115            Taurus
3  Marge   36  939-555-0116            Pisces